kbtin-1.0.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1449,7 +1449,7 @@ fi
 
 PACKAGE=KBtin
 
-VERSION=1.0.2
+VERSION=1.0.3
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { { echo "$as_me:$LINENO: error: source directory already configured; run \"make distclean\" there first" >&5
@@ -3894,8 +3894,8 @@ done
 
 
 
-{ echo "$as_me:$LINENO: checking for ptyranges..." >&5
-echo "$as_me: checking for ptyranges..." >&6;}
+echo "$as_me:$LINENO: checking ptyranges" >&5
+echo $ECHO_N "checking ptyranges... $ECHO_C" >&6
 if test -d /dev/ptym ; then
 pdir='/dev/ptym'
 else
@@ -3934,6 +3934,11 @@ cat >>confdefs.h <<_ACEOF
 #define PTYRANGE1 "$p1"
 _ACEOF
 
+echo "$as_me:$LINENO: result: $p0,$p1" >&5
+echo "${ECHO_T}$p0,$p1" >&6
+else
+echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
 fi
 
 
@@ -4539,6 +4544,43 @@ _ACEOF
 
 fi
 
+
+
+echo "$as_me:$LINENO: checking whether inline functions can be used extern" >&5
+echo $ECHO_N "checking whether inline functions can be used extern... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+
+extern inline void blah();int main(){return 0;}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define EXT_INLINE
+_ACEOF
+
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
 
 
           ac_config_files="$ac_config_files Makefile"
